import './globals.css';

import type { Metadata, Viewport } from 'next';
import { UIProvider } from '@whisper-loop/web-ui/components';
import { Noto_Sans, Noto_Sans_Mono } from 'next/font/google';
import { cn } from '@whisper-loop/web-ui/utils';
import uiConfig from '@/configs/ui';

const notoSans = Noto_Sans({
  variable: '--font-noto-sans',
  subsets: ['latin']
});

const notoMono = Noto_Sans_Mono({
  variable: '--font-noto-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export const viewport: Viewport = {
  maximumScale: 1
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(notoSans.variable, notoMono.variable, 'antialiased')}
      suppressHydrationWarning
    >
      <body>
        <UIProvider
          globalTokenConfig={uiConfig.globalTokenConfig}
          componentThemeConfig={uiConfig.componentThemeConfig}
          themeProviderProps={{
            attribute: ['class', 'data-theme']
          }}
        >
          {children}
        </UIProvider>
      </body>
    </html>
  );
}
